keycloak:
  realm: Biobank
  auth-server-url: http://${MYSQL_HOST}:8180/auth
  resource: sprec-sample
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-sprec]
      securityCollections:
        - name: Sprecsample private API's
          patterns: ['/sprecsample/*']

spring:
  jpa:
    hibernate:
      generate-ddl: false
  datasource:
      url: jdbc:mysql://${MYSQL_HOST}:3306/sprecsample_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: admin
      password: admin
      initialization-mode: always

server:
  port: 9094