keycloak:
  realm: Biobank
  auth-server-url: http://localhost:8180/auth
  resource: sprec-sample
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-sprec]
      securityCollections:
        - name: Sprecsample private API's
          patterns: ['/sprecsample/*']

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
      url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: administrator
      initialization-mode: always

server:
  port: 9094